server.port=8080

spring.output.ansi.enabled=ALWAYS
spring.profiles.active=dev
spring.jpa.open-in-view=false

# openweathermap config
open-api.base-url=https://api.openweathermap.org
open-api.app-id="api key"

# homeassistant config
home-assistant.base-url=http://homeassistant2:8123
home-assistant.temperature-endpoint=/api/states/sensor.temperatura_pokoj_hdc1080_temperature
home-assistant.humidity-endpoint=/api/states/sensor.temperatura_pokoj_hdc1080_humidity
home-assistant.auth-token="token"
home-assistant.data-fetch-cron=0 */1 * * * *

logging.level.root=info
logging.file.path=./LOGS/

spring.jpa.properties.hibernate.column_ordering_strategy=legacy