spring.datasource.url=jdbc:postgresql://localhost:5432/chata_database
spring.datasource.username=chata_database
spring.datasource.password=pgbercik6

spring.jpa.hibernate.ddl-auto = none

# openweathermap config
open-api.fetch-weather-interval=0 */1 * * * ?
open-api.app-id=b952190645b5d58b50b9c3bd143565e0

# homeassistant config
home-assistant.auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ODM3ZGQzY2Y0YTU0YzJhOTI3ZjZkMjNkN2Q3YzE4NCIsImlhdCI6MTcyNzAxNjY4MSwiZXhwIjoyMDQyMzc2NjgxfQ.EybgiiW2plT9SYZMTNBpgW-iztMMZyO2DF6TcmZMF28
#home-assistant.data-fetch-cron=-