url=jdbc:postgresql://localhost:5432/chata_database
username=chata_database
password=pgbercik6

changeLogFile=database/changelog/db.changelog-master.xml
contexts=dev,test,prod
databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK