url=@spring.datasource.url@
username=@spring.datasource.username@
password=@spring.datasource.password@
driver=org.postgresql.Driver

changeLogFile=database/changelog/db.changelog-master.xml
contexts=dev,test,prod
databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK